### ISSUE TITLE
Create example of vite implmentatio

### ISSUE THREAD

**Issue by raulcesar54** [Telefonica/mistica-web#1058]
We need an example of how we can integrate Mistica into Vite projects, if possible.

Using: https://vitejs.dev/guide/
Vite React and TS: https://stackblitz.com/edit/vitejs-vite-yuu9xg?file=index.html&terminal=dev

**Comment by raulcesar54** [comment]
Example created, however, PR closed due to lack of merge

**Comment by marcoskolodny** [comment]
@raulcesar54 have you checked the errors shown in the in the PR checks? Do you need any help regarding this?

**Comment by raulcesar54** [comment]
@marcoskolodny Hello, yes, I validated and updated the branch. Thank you for your help!

**Comment by marcoskolodny** [comment]
@raulcesar54 the issues are still there. Merging master to your branch won't fix them, since the errors are related to your changes.

We've decided that we will create a task for us to build this example based on the code you wrote. Thank you for your help! :)
