### ISSUE TITLE
Image: add srcSet attribute to allow images for different DPI devices

### ISSUE THREAD

**Issue by dominik-petschenka-syzygy** [Telefonica/mistica-web#1085]
To save bandwidth, we would like to use different sources for small and large displays or for low and high pixel density displays.

The Image component should support `srcSet` just like the existing `src` prop.

**Comment by atabel** [comment]
hi @dominik-petschenka-syzygy, thanks for reporting. We'll take a look https://jira.tid.es/browse/WEB-1842
