### ISSUE TITLE
Allow selecting chips with badges

### ISSUE THREAD

**Issue by jerome-gelmar-syzygy** [Telefonica/mistica-web#1123]
The current behavior of the Chip component is that it becomes non-selectable (relates to the color change of the chip) once a `badge` or an `onClose` action is set. However, there are scenarios where users might want to select a chip even if it has a badge.

For example, when using the badge as a filter, it would be useful to still allow chip selection.

This enhancement would provide more flexibility for users who want to use badges as filters while still allowing chip selection.

**Comment by atabel** [comment]
hi @jerome-gelmar-syzygy, can you open a discussion here instead?
https://github.com/Telefonica/mistica-design/discussions

Are you working fo Telefonica? in which project are you using Mistica?

**Comment by aweell** [comment]
Hi @jerome-gelmar-syzygy, 

We've created a ticket to allow chip selection when they have a badge: https://jira.tid.es/browse/WEB-1880

**Comment by jerome-gelmar-syzygy** [comment]
Hi @aweell,

sry the topic has unfortunately gone under my radar. Thank you very much for creating a ticket.

**Comment by marcoskolodny** [comment]
Merged in https://github.com/Telefonica/mistica-web/pull/1134
