### ISSUE TITLE
Support Image srcset prop in PosterCard

### ISSUE THREAD

**Issue by walter-restifo-syzygy** [Telefonica/mistica-web#1138]
Hi guys,

I'm a developer of SYZYGY Techsolution  working for O2.
In #1109 you have added the srcset attribute to the Image component. It would be nice, if you can implement the srcset in the Image of the PosterCard component, so that we can use responsive images in this component too.

This is the [code](https://github.com/Telefonica/mistica-web/blob/cb21eba313024ed525b93298d0bdf8b86e815b5e/src/card.tsx#L235C8-L235C9)

**Comment by marcoskolodny** [comment]
This has been developed in https://github.com/Telefonica/mistica-web/pull/1253

Thanks for your feedback!
