### ISSUE TITLE
SearchField: support inputMode prop

### ISSUE THREAD

**Issue by irina-stelea-syzygy** [Telefonica/mistica-web#1194]
Hello, 

I'm part of the Syzygy Techsolutions dev team working for Telefonica projects.

In one of our features we use the SearchField component and we need to trigger the appearance of the appropriate keyboard when the user inputs something into the field. 
It would be helpful if the typing of the component could explicitly support the "inputMode" prop.

Thank you for considering this!

**Comment by marcoskolodny** [comment]
This has been developed in https://github.com/Telefonica/mistica-web/pull/1249

Thanks for your feedback!
