### ISSUE TITLE
Breaking changes for 13.0.0

### ISSUE THREAD

**Issue by pladaria** [Telefonica/mistica-web#572]
* [x] https://github.com/Telefonica/mistica-web/pull/612
    * we have a codemod for this: https://github.com/Telefonica/mistica-web/blob/master/codemods/theme-colors-codemod.js
* [x] https://github.com/Telefonica/mistica-web/pull/615
* [x] Distribute VE styles as a `css/mistica.css` file and stop embedding it in the js. https://github.com/Telefonica/mistica-web/pull/614
* [x] Remove `ThemeConfig.mediaQueries` https://github.com/Telefonica/mistica-web/pull/613
* [x] Change `ThemeConfig.colorScheme` to `'auto'` by default https://github.com/Telefonica/mistica-web/pull/612
* [x] https://github.com/Telefonica/mistica-web/pull/616
* [x] Remove padding in `DataCard` and `MediaCard` in `extra` prop: https://github.com/Telefonica/mistica-web/pull/621
* [x] https://github.com/Telefonica/mistica-web/pull/620
* [x] Deprecated chevron-top-regular (repeated with chevron-up-regular) https://github.com/Telefonica/mistica-web/pull/618
* [x] Rename borderLight and borderDark

**Comment by atabel** [comment]
https://github.com/Telefonica/mistica-web/releases/tag/v13.0.0
