### ISSUE TITLE
`examples` are not referenced in the README.md

### ISSUE THREAD

**Issue by jmendiara** [Telefonica/mistica-web#639]
The `examples` directory is a great Quickstart for newbies and people coming here for 1st time. 

But it's not referenced in any place in the `README.md`, making hard to find it.

I'll be glad to contribute with it.

**Comment by atabel** [comment]
feel free to send a PR ;)

**Comment by atabel** [comment]
fixed in https://github.com/Telefonica/mistica-web/pull/645
