### ISSUE TITLE
Add 'REF' in another fields

### ISSUE THREAD

**Issue by augustocmarinho-tlf** [Telefonica/mistica-web#668]
Hola! 
 

Estamos tratando de usar la propiedad 'ref' en un SearchField, pero no existe mapeado.
Solo en TextField.
¿Es posible que también esté disponible en SearchField?
 
![image](https://user-images.githubusercontent.com/115249527/219658248-1cd23570-2de0-4ce6-9920-dbfd2cbf2486.png)

No hay 'ref' en SearchField
![image](https://user-images.githubusercontent.com/115249527/219658328-3ada74d9-3a8b-482b-b38e-80aa8284117a.png)

¡Muchas gracias!

**Comment by atabel** [comment]
fixed in https://github.com/Telefonica/mistica-web/pull/673
