### ISSUE TITLE
Form component - loading behavior on submit

### ISSUE THREAD

**Issue by CamilaQueiroz** [Telefonica/mistica-web#842]
Using the **Form** component, when passing a function to the **onSubmit** prop, the form keeps loading without stopping. I don't know if it's related, but I've monitored the formStatus prop of useForm and it doesn't change from filling to sending when I submit the form. **I'm using Next.js 13**

**To Reproduce** Steps to reproduce the behavior:

1. Use Form component like the example below

```

function Login() {
  const { SignIn } = useAuth();
  const router = useRouter();

  const onSubmit = async (data: FormValues) => {
    try {
      await SignIn(data as SignInProps);
      router.push("/dashboard");

    } catch (error) {
      alert("Credenciais inválidas");
    }
  };

  return (
    <>
      <Form
        onSubmit={onSubmit}
        id="login-form"
        initialValues={{ email: "", password: "" }}
      >
        <Stack space={16}>
          <EmailField label="e-mail" name="email" id="email" />

          <PasswordField label="senha" id="password" name="password" />

          <ButtonLayout>
            <ButtonPrimary submit loadingText="Sending">
              Login
            </ButtonPrimary>
          </ButtonLayout>
        </Stack>
      </Form>
    </>
  );
}





```
**Expected behavior**  Form component change the "loading" behavior when finished the function

<img width="442" alt="Captura de Tela 2023-08-03 às 16 17 08" src="https://github.com/Telefonica/mistica-web/assets/20759520/4fed90b3-c54c-479f-bc1b-3f44ccb5aeb0">

**Desktop (please complete the following information):**

- OS: MacOS Ventura 13.2
- Browser: chrome, safari

**Comment by CamilaQueiroz** [comment]
Looking for more information, I understood that this is the behavior of the Form component. I found this explanation in an example:

 - When the form is being submitted (while the onSubmit promise is unresolved or rejected), all fields are automatically disabled and a spinner appears inside the submit button.

https://github.com/Telefonica/mistica-web/blob/master/doc/forms.md#important-notes


But is there any way to handle this behavior? I tried to manipulate the props "disable" and "showSpinner" but no success.

**Comment by atabel** [comment]
this is the expected behavior. If you want the form to be usable again you need to resolve the onSubmit promise.
See this example:
https://mistica-web.vercel.app/playroom#?code=N4Igxg9gJgpiBcIA8AxCAnAtgHQHYAJ8JcBlAVwCNMBLAFwF5gBDAZwE9cx8AKAMw0wARJrSYBKfPQB8%2BYHkKEmAdyZ18uGEvwAFdBBosY3buhgsIAGwBuMCdPyHaAFWqYYEMrRNnLNgDT4AEwADKFiYgDc8vgAvjF4UtFIAEIQAB74AA5MUFDUuADmjACMAGwxiQQKSCSiYADWDtlgMCXllQrVTjBptCjUMBZQ6kxu9NgguKMwE-gWTBSD4yAActOzAPQdnfhIAKKYqhb9g8NTYxMwh9QWs-OLFsswALTXtyD4W9GdKZ60xAAZJhsDy0bY7XbJP7EXSuJjoNgOSg0MEkGC4KBIDZQ2j-XCww4I8HVbHQ3BAkGeYlY2pMBrbLGpNKVLFoLCVEB%2BEC0AAWVzMCAA2iAAPKBEAAXS5SmoUF5LCFAGZSsE-MVgoEACwSmJAA

In your example, I suspect `SignIn` doesn't resolve/reject

**Comment by CamilaQueiroz** [comment]
Hi @atabel, even resolving the promise the behavior continues.

One more example: 

```

function Register() {

  return (
    <Stack space={16}>
      <Form
        onSubmit={async (formData) => {
          await new Promise((resolve) => setTimeout(resolve, 2000));
        }}
      >
        <TextField label="CNPJ" name="registeredNumber" />

        <ButtonPrimary submit>Cadastrar</ButtonPrimary>
      </Form>
    </Stack>
  );
}

export default Register;

```


<img width="284" alt="Captura de Tela 2023-08-11 às 08 45 20" src="https://github.com/Telefonica/mistica-web/assets/20759520/2dcdbdca-8352-4005-a771-8f860bce471f">

**Comment by atabel** [comment]
that's weird, I can not reproduce it in playroom

**Comment by CamilaQueiroz** [comment]
Could this be because of the version? I'm using ^14.19.0.

I will try to create a test environment

**Comment by CamilaQueiroz** [comment]
https://github.com/CamilaQueiroz/mistica-form-component-test

@atabel, You can check here in this repository, I created a very simple environment.

**Comment by atabel** [comment]
which version? have you tried 14.22.0?
